@startuml
'https://plantuml.com/class-diagram

object RoboRally_Game {

}

object Player {
    CheckPointToken
}

object Register {

}

object Robot {
}

object Board {
    RacingCourse
    Phase (programming or activasion)
}

object Programming_Card {

}

object Special_Programming_Card {

}


object Space {
    Elements
}

abstract Card {

}

object Player_Mat {

}

RoboRally_Game"1" -- "2..6"Player : plays
RoboRally_Game"1"-- "1"Board : has
Board"1" *-- "1..*"Space : has
Board"1" *-- "1..*"Card : has
Space"1" - "0..1"Robot : has
Player"1" -L- "1"Robot : has
Player_Mat"1" -- "1"Player : has
Player_Mat"1" -- "5"Register : has
Card <|--- Programming_Card
Card <|--- Special_Programming_Card
Card"0..1" -- "1"Register : has
Player_Mat"1" -- "1"Board : has

@enduml